import LeftSide from '@/components/LeftSide'
import Navbar from '@/components/Navbar'
import RightSide from '@/components/RightSide'
import Head from 'next/head'
import { motion } from 'framer-motion'
import Banner from '@/components/Banner'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Archieve from '@/components/Archieve'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Skills from '@/components/Skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vanel Nwaba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myPicture.ico" />
      </Head>
      <main className="w-full h-screen font-bodyFont text-textLight overflow-x-hidden overflow-y-scroll main">
           <Navbar />
           <div className='w-full h-[90vh] xl:flex items-center gap-20 justify-between'>
            <motion.div 
              initial={{opacity:0}} 
              animate={{opacity:1}} 
              transition={{delay:1.4}}
              className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'
            >
              <LeftSide />
            </motion.div>
            <div className='h-[90vh] w-full mx-auto p-4'>
              <Banner />
              <About />
              {/* {Skills} */}
              <Skills />
              <Projects />
              {/* {Achieve} */}
              {/* <Archieve /> */}
              {/* {Contact} */}
              <Contact />
              {/* {Footer} */}
              <Footer />
            </div>
            <motion.div 
              initial={{opacity:0}} 
              animate={{opacity:1}} 
              transition={{delay:1.4}}
              className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'
            >
              <RightSide />
            </motion.div>
           </div>
      </main>
    </>
  )
}
